# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Code...'
tagline:          ''
description:      'Random snippets of code that I have played around with to analysis or build with.
<a href="https://twitter.com/jslessels" target="_blank">@jslessels</a>'
baseurl:          /

author:
  name:           'Jason Lessels'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde