# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Code...'
tagline:          ''
description:      'Bits of code documented for future reference.
<a href="https://twitter.com/jslessels" target="_blank">@jslessels</a>'
baseurl:          /

author:
  name:           'Jason Lessels'

paginate:            3

markdown: kramdown

